POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": "Um evento de uma única pessoa",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/602cf313-199f-40c3-86a5-ec035b429fc1/attendees
Content-Type: application/json

{
  "name": "Isis Fraga",
  "email": "isis.fraga@gmail.com"
}